// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALMXiy25ysyhgp57Ah6BOrD9whVlif-9E',
    appId: '1:795697834067:web:4be58a716c388f3d437ea6',
    messagingSenderId: '795697834067',
    projectId: 'shopping-f4ee9',
    authDomain: 'shopping-f4ee9.firebaseapp.com',
    storageBucket: 'shopping-f4ee9.appspot.com',
    measurementId: 'G-0YEK9QMLS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVFOd2rZABPNrMwXi8foikau2TGpmora0',
    appId: '1:795697834067:android:6ace132101505619437ea6',
    messagingSenderId: '795697834067',
    projectId: 'shopping-f4ee9',
    storageBucket: 'shopping-f4ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdBGHHkHJiG_BJpk6-s17YDcSU0swqHaE',
    appId: '1:795697834067:ios:6235e92a982d57c8437ea6',
    messagingSenderId: '795697834067',
    projectId: 'shopping-f4ee9',
    storageBucket: 'shopping-f4ee9.appspot.com',
    iosBundleId: 'com.example.ecommerceMobileApp',
  );
}
